## Links and file names for software thats downloaded outside of repositories

## Drivers/Hardware etc
COOLERCONTROL_LINK="https://copr.fedorainfracloud.org/coprs/codifryed/CoolerControl/repo/fedora-40/codifryed-CoolerControl-fedora-40.repo"
COOLERCONTROL_FILE="codifryed-CoolerControl-fedora-40.repo"

OPENRGB_LINK="https://openrgb.org/releases/release_0.9/openrgb_0.9_amd64_bookworm_b5f46e3.deb"
OPENRGB_DEB="openrgb_0.9_amd64_bookworm_b5f46e3.deb"

### gaming
WOWUPLINK="https://github.com/WowUp/WowUp.CF/releases/download/v2.20.0/WowUp-CF-2.20.0.AppImage"
WOWUPBINARY="WowUp-CF-2.20.0.AppImage"

WACOMPLINK="https://github.com/WeakAuras/WeakAuras-Companion/releases/download/v5.2.3/WeakAuras-Companion-5.2.3.AppImage"
WACOMPBINARY="WeakAuras-Companion-5.2.3.AppImage"


WOWLOGSLINK="https://github.com/RPGLogs/Uploaders-warcraftlogs/releases/download/v8.5.16/warcraftlogs-v8.5.16.AppImage"
WOWLOGSBINARY="warcraftlogs-v8.5.16.AppImage"

### development

SCENE_BUILDER_RPM_LINK="https://download2.gluonhq.com/scenebuilder/22.0.0/install/linux/SceneBuilder-22.0.0.rpm"
SCENE_BUILDER_DEB_LINK="https://download2.gluonhq.com/scenebuilder/22.0.0/install/linux/SceneBuilder-22.0.0.deb"

IDEA_LINK="https://download.jetbrains.com/idea/ideaIC-2024.2.1.tar.gz"

NETBEANS_LINK="https://dlcdn.apache.org/netbeans/netbeans/22/netbeans-22-bin.zip"

PYCHARM_LINK="https://download.jetbrains.com/python/pycharm-community-2024.2.1.tar.gz"

ECLIPSE_LINK="https://mirror.csclub.uwaterloo.ca/eclipse/oomph/epp/2024-09/R/eclipse-inst-jre-linux64.tar.gz"
