## Links and file names for software thats downloaded outside of repositories


### gaming
WOWUPLINK="https://github.com/WowUp/WowUp.CF/releases/download/v2.11.0/WowUp-CF-2.11.0.AppImage"
WOWUPBINARY="WowUp-CF-2.11.0.AppImage"

MINECRAFT_LINK="https://launcher.mojang.com/download/Minecraft.tar.gz"
MINECRAFT_ARCHIVE="Minecraft.tar.gz"


### office
BITWARDEN_LINK="https://github.com/bitwarden/clients/releases/download/desktop-v2024.2.0/Bitwarden-2024.2.0-x86_64.AppImage"
BITWARDEN_BINARY="Bitwarden-2024.2.0-x86_64.AppImage"

### coding

SCENE_BUILDER_RPM_LINK="https://download2.gluonhq.com/scenebuilder/20.0.0/install/linux/SceneBuilder-20.0.0.rpm"
SCENE_BUILDER_DEB_LINK="https://download2.gluonhq.com/scenebuilder/21.0.0/install/linux/SceneBuilder-21.0.0.deb"

IDEA_LINK="https://download.jetbrains.com/idea/ideaIC-2023.3.4.tar.gz"
NETBEANS_LINK="https://dlcdn.apache.org/netbeans/netbeans/20/netbeans-20-bin.zip"

PYCHARM_LINK="https://download.jetbrains.com/python/pycharm-community-2023.3.2.tar.gz"

ECLIPSE_LINK="https://eclipse.mirror.rafal.ca/oomph/epp/2023-09/R/eclipse-inst-jre-linux64.tar.gz"